#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'

options = {
   :app_name   => "hackprintd",
   :dir_mode   => :script,
   :dir        => 'pids',
   :multiple   => false,
   :ontop      => false,
   :mode       => :load,
   :backtrace  => true,
   :monitor    => true
 }

Daemons.run(File.join(File.dirname(__FILE__), 'listener.rb'), options)
